if [ ! -f "$ZDOTDIR"/.zshrc.zwc -o "$ZDOTDIR"/.zshrc -nt "$ZDOTDIR"/.zshrc.zwc ]; then
  zcompile "$ZDOTDIR"/.zshrc
fi

umask 022
bindkey -e

autoload -Uz compinit && compinit
autoload -Uz colors && colors
autoload -Uz add-zsh-hook
autoload -Uz vcs_info
autoload -Uz bracketed-paste-magic
zle -N bracketed-paste bracketed-paste-magic
autoload -Uz url-quote-magic
zle -N self-insert url-quote-magic

zstyle ':prezto:module:git:alias' skip 'yes'
if [ ! -f "${HOME}/.zgen/zgen.zsh" ]; then
  git clone https://github.com/tarjoilija/zgen.git "${HOME}/.zgen"
fi

# zgen configuration
source "$HOME/.zgen/zgen.zsh"
if ! zgen saved; then
  zgen prezto prompt theme 'damoekri'
  zgen prezto
  zgen prezto editor
  zgen prezto prompt
  zgen prezto completion

  zgen load zsh-users/zsh-completions
  zgen load zdharma-continuum/fast-syntax-highlighting
  zgen load rupa/z
  zgen load mollifier/anyframe
  zgen load zsh-users/zsh-autosuggestions
  zgen load jonmosco/kube-ps1

  zgen save
fi

# option
setopt correct
setopt no_beep
setopt magic_equal_subst
setopt hist_ignore_dups
setopt hist_reduce_blanks
setopt prompt_subst
setopt share_history

# alias
alias bd='cd ..'
alias bat='bat --style="header,numbers,grid"'
alias ls='exa --icons --git'
alias lsa='exa -a --icons --git'
alias ll='exa -ahl --icons --git'
alias lt='exa -T -L 3 -a --icons -I "node_modules|.git|.cache"'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias ga='git add'
alias gb='git branch'
alias gcm='git commit'
alias gcma='git commit --amend'
alias gf='git fetch'
alias gs='git switch'
alias gr='git restore'
alias grb='git rebase'
alias grt='cd "$(git rev-parse --show-toplevel || echo .)"'
alias gst='git status'
alias gpr='gh prs'
alias gl='git l'
alias gpl='git pull'
alias gplr='git pull -rebase'
alias k='kubectl'
alias kx='kubectx'
alias kn='kubens'
alias d='docker'
alias dc='docker compose'
alias tf='terraform'
alias grep='rg -i'
alias mysql='mycli'
alias gcc='gcc -Wall'
alias sk='skaffold'
alias ks='kustomize'
alias kp='kube-prompt'
alias jq='jq -C'
alias tffmt="terraform fmt -write=true -recursive"
alias relogin="exec $SHELL -l"

# anyenv
if [ -d "$ANYENV_DEFINITION_ROOT" ]; then
  eval "$(anyenv init -)"
fi

# z
if [ ! -e "$XDG_DATA_HOME/z" ]; then
  mkdir -p $XDG_DATA_HOME/z
fi

# enable kubectl completion
source <(kubectl completion zsh)

# anyframe
zstyle ':anyframe:selector' use fzf
bindkey '^g^b' anyframe-widget-checkout-git-branch
bindkey '^g^g' anyframe-widget-cd-ghq-repository

# GNU commands
alias sed='gsed'

# vcs_info
PROMPT='%F{cyan}$(prompt-pwd) '
zstyle ':vcs_info:git:*' check-for-changes true
zstyle ':vcs_info:git:*' stagedstr '%F{yellow}+'
zstyle ':vcs_info:git:*' unstagedstr '%F{red}+'
zstyle ':vcs_info:*' formats '%F{green}[%b]%c%u'
zstyle ':vcs_info:*' actionformats '[%b|%a]'
add-zsh-hook precmd vcs_info 
PROMPT=$PROMPT'${vcs_info_msg_0_}%F{green}${editor_info[keymap]} '

zle_highlight+=(paste:none)

if [ -z "$_kubeps1" ]; then
  PROMPT='$(kube_ps1)'$PROMPT
  _kubeps1=true
fi

# enable complement during typing
autoload -Uz history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^p" history-beginning-search-backward-end
bindkey "^n" history-beginning-search-forward-end

# for homebrew m1
ARCH=$(uname -m)
if [ "$ARCH" = "arm64" ]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# bookmark
# this is inspired by https://threkk.medium.com/how-to-use-bookmarks-in-bash-zsh-6b8074e40774
# make bookmark symbolic link  by `ln -s path/to/certain/directory/with/my/project ~/.bookmarks/@important-project`
mkdir -p "$HOME/.bookmarks"
if [ -d "$HOME/.bookmarks" ]; then
  export CDPATH=".:$HOME/.bookmarks"
  alias goto="cd -P"
fi

# fd with fzf
function fd-fzf() {
  local target_dir=$(fd -t d -I -H -E ".git"| fzf-tmux --reverse --query="$LBUFFER")
  local current_dir=$(pwd)

  if [ -n "$target_dir" ]; then
    BUFFER="cd ${current_dir}/${target_dir}"
    zle accept-line
  fi

  zle reset-prompt
}
zle -N fd-fzf
bindkey "^n" fd-fzf

# nvm
mkdir -p "$HOME/.nvm"
export NVM_DIR="$HOME/.nvm"
if [ "$ARCH" = "arm64" ]; then
  [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"
  [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"
else
  [ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
fi
